# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  cargo-create-tauri-app = {
    pname = "cargo-create-tauri-app";
    version = "create-tauri-app-v4.5.9";
    src = fetchFromGitHub {
      owner = "tauri-apps";
      repo = "create-tauri-app";
      rev = "create-tauri-app-v4.5.9";
      fetchSubmodules = false;
      sha256 = "sha256-S+3BfgddISWf+HrTT3oq0m80Fb17AVtMrxjY2chhVa8=";
    };
    "Cargo.lock" = builtins.readFile ./cargo-create-tauri-app-create-tauri-app-v4.5.9/Cargo.lock;
  };
  kwok = {
    pname = "kwok";
    version = "v0.6.1";
    src = fetchFromGitHub {
      owner = "kubernetes-sigs";
      repo = "kwok";
      rev = "v0.6.1";
      fetchSubmodules = false;
      sha256 = "sha256-RVyXGPT30Fz+K1VdMneYldXvzHyimuCX406DMKOtUq4=";
    };
  };
}
