# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  cargo-create-tauri-app = {
    pname = "cargo-create-tauri-app";
    version = "create-tauri-app-v4.5.3";
    src = fetchFromGitHub {
      owner = "tauri-apps";
      repo = "create-tauri-app";
      rev = "create-tauri-app-v4.5.3";
      fetchSubmodules = false;
      sha256 = "sha256-JjAKIsdAtgEFXz5dBW+Ve2IpAJ0nCYXTSnEq2XFJ3xg=";
    };
    "Cargo.lock" = builtins.readFile ./cargo-create-tauri-app-create-tauri-app-v4.5.3/Cargo.lock;
  };
  kwok = {
    pname = "kwok";
    version = "v0.6.0";
    src = fetchFromGitHub {
      owner = "kubernetes-sigs";
      repo = "kwok";
      rev = "v0.6.0";
      fetchSubmodules = false;
      sha256 = "sha256-3g8enPxxh2SaxiDgDwJpAfSjv/iRoBRmTnXwDtuMdFA=";
    };
  };
}
